Create contact form section validate inputs formspree service
evillaz/evillaz.github.io pull request #4
Opened 2023-01-17 20:57 UTC by evillaz

This branch's purpose was to:
- Use flexbox for the structure design
- Implement button behavior(hover, active)
- Create a contact form section
   -  Added name, email, text and submit button elements.
   - validate the length of the fields
   - Submit data using formspree service
- Create a footer section
   - Added social media icons and background shapes.

2023-01-17 21:41 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @evillaz, 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 21:41 UTC, anagudelogu commented on index.html
> +        </ul>
- [ ] Great job working on this section! 🚀 However, I think that using a `<ul>` tag here is not semantically correct as these elements don't represent a list. I suggest you remove the list and keep the section as your flex container for the paragraph and the form! 🤓 🔧

2023-01-17 21:41 UTC, anagudelogu commented on index.html
> +            </form>
- [ ] You did an excellent job using `Formspree` to collect data! 🥇 I would only suggest that you style a bit the `<textarea>` so it matches the Figma design:

|Template|Your design|
|---|---|
| ![image](https://user-images.githubusercontent.com/77069011/213017945-bc36fed4-532a-40f0-b3e7-6e82665bea0b.png) | ![Screenshot from 2023-01-17 16-34-05](https://user-images.githubusercontent.com/77069011/213017877-07f2a513-d618-48b3-b0b4-0260ccbeb9ca.png) |


As you can see, your `<textarea>` is half the height of the Figma design, please fix it as well as the color of the social media icons! 🤓 🔧

2023-01-17 22:28 UTC, evillaz commented
@anagudelogu Hello and thank you for reviewing. I have one question, is it ok if I use ul for the elements inside the form like this?
![ul](https://user-images.githubusercontent.com/119948733/213026236-a6c31304-37db-4ccf-ad28-06c026e20d89.png)

2023-01-17 23:02 UTC, GedeonTS requested changes
# STATUS: CHANGES REQUIRED :recycle: :

Hi @evillaz , 

Good job implementing some of the changes suggested by the previous reviewer!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif">

## Highlights :tophat:  :+1: 
- Good PR message  :+1: 
- Good UI design :+1: 
- No linter errors :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 23:02 UTC, GedeonTS commented on index.html
> +            </li>
- [ ] As requested by the previous reviewer [here](https://github.com/evillaz/my-portfolio/pull/4#discussion_r1072856120), kindly remove the unordered list syntax to make your project semantically correct:

here is how the code might be :+1: 

```
<form>
<input/>
<input/>
<textarea ></textarea>
<button>Get in touch</button>
</form>


```

2023-01-18 00:53 UTC, DuaneDave approved these changes
Hi @evillaz  👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Form is working as expected
✔️ Very descriptive PR heading and summary
✔️ All linters check are passing


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 06:57 UTC, merged